# fly.toml app configuration file generated for thrive-goals on 2024-07-26T19:13:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thrive-goals'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 4321
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
